version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update
      - apt-get -y install zip
  build:
    commands:
      - echo Entered the build phase...
      - export REVISION_ID=`echo $REVISION | sed 's/\//-/g'`
      - pip install -U -t ./build -r requirements.txt 
      - ln -s -f -r -t ./build/ function.py
      - cd ./build && zip -r ${CODEBUILD_SRC_DIR}/useraction-reciever.zip .
artifacts:
  files:
    - ${CODEBUILD_SRC_DIR}/useraction-receiver.zip
  discard-paths: yes
